[project]
name = "app"
version = "1"
description = "The video-transcoder is a containerized microservice responsible for performing media transcoding and thumbnail generation as part of the video processing pipeline."
authors = [
    {name = "AJAY",email = "ajaychandran2019@gmail.com"}
]
license = {text = "It is designed to run as a disposable, isolated worker for each video file, typically spawned by the video-processing-service via Docker.1"}
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "redis (>=6.2.0,<7.0.0)",
    "ffmpeg (>=1.4,<2.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "boto3 (>=1.39.4,<2.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "netflix-platform-messaging-sdk @ git+https://github.com/Ajaychandran0/netflix-platform-messaging-sdk.git@v0.1.2"

]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
