from enum import StrEnum

class VideoEventType(StrEnum):
    PROCESSING_STARTED = "VIDEO_PROCESSING_STARTED"
    STAGE_CHANGED = "VIDEO_PROCESSING_STAGE_CHANGED"
    PROCESSING_COMPLETED = "VIDEO_PROCESSING_COMPLETED"
    PROCESSING_FAILED = "VIDEO_PROCESSING_FAILED"