from enum import StrEnum

class ProcessingStage(StrEnum):
    DOWNLOADING = "DOWNLOADING"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    TRANSCODING = "TRANSCODING"
    GENERATING_PLAYLIST = "GENERATING_PLAYLIST"
    GENERATING_THUMBNAIL = "GENERATING_THUMBNAIL"
    UPLOADING_ASSETS = "UPLOADING_ASSETS"
    CLEANUP = "CLEANUP"