export enum ErrorCodes {
    SERVICE_ERROR = 'SERVICE_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    INVALID_TOKEN = 'INVALID_TOKEN',

    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  }

  export enum SuccessCodes {
    USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  }
  