from enum import StrEnum


class ProcessingEvent(StrEnum):
    PROCESSING_STARTED = "VIDEO_PROCESSING_STARTED"
    STAGE_CHANGED = "VIDEO_PROCESSING_STAGE_CHANGED"
    PROCESSING_COMPLETED = "VIDEO_PROCESSING_COMPLETED"
    PROCESSING_FAILED = "VIDEO_PROCESSING_FAILED"
    
class ProcessingStage(StrEnum):
    DOWNLOADING = "DOWNLOADING"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    TRANSCODING = "TRANSCODING"
    GENERATING_PLAYLIST = "GENERATING_PLAYLIST"
    GENERATING_THUMBNAIL = "GENERATING_THUMBNAIL"
    UPLOADING_ASSETS = "UPLOADING_ASSETS"
    CLEANUP = "CLEANUP"
    